import React, { useState, useEffect } from 'react';
import {
  HiOutlineDocumentArrowDown,
  HiOutlineMagnifyingGlass,
  HiOutlineCloudArrowUp,
  HiOutlineTrash,
  HiOutlineXMark,
  HiOutlineArrowPath,
  HiOutlineDocumentText
} from 'react-icons/hi2';
import { jsPDF } from 'jspdf';
import api from '../../api/axiosInstance';
import toast from 'react-hot-toast';

export default function DownloadCenter() {
  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('All');
  const [search, setSearch] = useState('');
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    title: '',
    type: 'Study Material',
    class_name: 'All Classes',
    description: '',
    file_size: '1.5 MB'
  });

  useEffect(() => {
    fetchDownloads();
  }, []);

  const fetchDownloads = async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/downloads');
      if (Array.isArray(data)) {
        setDocuments(data);
      }
    } catch (err) {
      console.error('Failed to load downloads:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleUploadSubmit = async (e) => {
    e.preventDefault();
    if (!formData.title) {
      toast.error('Document title is required');
      return;
    }

    setSubmitting(true);
    try {
      const { data } = await api.post('/downloads', formData);
      toast.success('Document uploaded to Download Center successfully!');
      setDocuments([data, ...documents]);
      setShowUploadModal(false);
      setFormData({
        title: '',
        type: 'Study Material',
        class_name: 'All Classes',
        description: '',
        file_size: '1.5 MB'
      });
    } catch (err) {
      console.error('Error uploading document:', err);
      toast.error('Failed to upload document');
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (id, title) => {
    if (!window.confirm(`Delete document "${title}"?`)) return;
    try {
      await api.delete(`/downloads/${id}`);
      toast.success('Document removed');
      setDocuments(prev => prev.filter(d => d.id !== id));
    } catch (err) {
      console.error('Delete error:', err);
      toast.error('Failed to delete document');
    }
  };

  const handleDownload = (docData) => {
    try {
      const doc = new jsPDF();
      const title = docData.title || 'Educational Document';
      
      // Header styling
      doc.setFillColor(79, 70, 229);
      doc.rect(0, 0, 210, 35, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text("SMART SCHOOL MANAGEMENT SYSTEM", 105, 18, { align: "center" });
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text("Official Digital Download Center • Academic Resources", 105, 26, { align: "center" });

      // Body styling
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(title, 20, 52);

      doc.setDrawColor(226, 232, 240);
      doc.line(20, 56, 190, 56);

      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`Document Category:  ${docData.type || 'General'}`, 20, 68);
      doc.text(`Target Classes:     ${docData.class_name || docData.class || 'All Classes'}`, 20, 78);
      doc.text(`Date of Release:    ${docData.created_at ? new Date(docData.created_at).toLocaleDateString() : docData.date || new Date().toLocaleDateString()}`, 20, 88);
      doc.text(`Document Reference: SS-DOC-${docData.id || 101}`, 20, 98);

      if (docData.description) {
        doc.setFont('helvetica', 'bold');
        doc.text("Description & Instructions:", 20, 114);
        doc.setFont('helvetica', 'normal');
        const splitDesc = doc.splitTextToSize(docData.description, 170);
        doc.text(splitDesc, 20, 122);
      }

      // Verification seal
      doc.setDrawColor(79, 70, 229);
      doc.rect(20, 160, 170, 35);
      doc.setTextColor(79, 70, 229);
      doc.setFont('helvetica', 'bold');
      doc.text("VERIFIED ACADEMIC RESOURCE", 105, 172, { align: "center" });
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.setFont('helvetica', 'normal');
      doc.text("This document is verified by Smart School Curriculum & Academic Directorate.", 105, 180, { align: "center" });
      doc.text("Authorized for student revision and classroom instruction.", 105, 186, { align: "center" });

      // Footer
      doc.setFontSize(9);
      doc.text("Generated by Smart School Download Center • Infosof Technologies 2026", 105, 285, { align: "center" });

      const fileName = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      doc.save(`${fileName}.pdf`);
      toast.success('Document downloaded successfully!');
    } catch(err) {
      console.error("PDF Download Error:", err);
      toast.error('Failed to download file');
    }
  };

  const filtered = documents.filter(d => {
    const q = search.toLowerCase();
    const matchSearch =
      !search ||
      (d.title && d.title.toLowerCase().includes(q)) ||
      (d.class_name && d.class_name.toLowerCase().includes(q)) ||
      (d.description && d.description.toLowerCase().includes(q));

    const matchTab = activeTab === 'All' || d.type === activeTab;
    return matchSearch && matchTab;
  });

  return (
    <div className="animate-fadeIn">
      <div className="page-header flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Download Center (Module 14)</h1>
          <p className="subtitle text-sm text-secondary">Manage curriculum syllabi, holiday assignments, question banks, and learning resources</p>
        </div>
        <div className="flex gap-2">
          <button className="btn btn-secondary flex items-center gap-1.5" onClick={fetchDownloads} disabled={loading}>
            <HiOutlineArrowPath size={16} className={loading ? 'animate-spin' : ''} />
            <span>Refresh</span>
          </button>
          <button className="btn btn-primary flex items-center gap-1.5" onClick={() => setShowUploadModal(true)}>
            <HiOutlineCloudArrowUp size={18} />
            <span>Upload Content</span>
          </button>
        </div>
      </div>

      <div className="card animate-slideUp">
        <div className="table-toolbar p-4 border-b border-secondary flex flex-wrap justify-between items-center gap-3">
          <div className="tabs mb-0 border-b-0 flex gap-2 overflow-x-auto">
            {['All', 'Syllabus', 'Assignments', 'Study Material', 'Other'].map(tab => (
              <button
                key={tab}
                className={`tab ${activeTab === tab ? 'active' : ''}`}
                onClick={() => setActiveTab(tab)}
              >
                {tab}
              </button>
            ))}
          </div>
          <div className="table-search" style={{ minWidth: '220px' }}>
            <HiOutlineMagnifyingGlass className="search-icon" />
            <input
              type="text"
              placeholder="Search documents..."
              value={search}
              onChange={e => setSearch(e.target.value)}
            />
          </div>
        </div>

        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>Content Title</th>
                <th>Category</th>
                <th>Target Class</th>
                <th>Upload Date</th>
                <th>File Size</th>
                <th className="text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan="6" className="text-center py-10 text-secondary">
                    <div className="inline-block animate-spin mr-2">⟳</div> Loading educational documents...
                  </td>
                </tr>
              ) : filtered.length === 0 ? (
                <tr>
                  <td colSpan="6" className="text-center py-10 text-secondary">
                    <HiOutlineDocumentText size={36} className="mx-auto text-tertiary opacity-40 mb-2" />
                    No files found in this category. Click "Upload Content" to publish materials.
                  </td>
                </tr>
              ) : (
                filtered.map(doc => {
                  const dateStr = doc.created_at
                    ? new Date(doc.created_at).toLocaleDateString()
                    : doc.date || '2026-09-26';

                  return (
                    <tr key={doc.id} className="hover:bg-hover transition-colors">
                      <td>
                        <div className="font-semibold text-sm text-primary-400">{doc.title}</div>
                        {doc.description && <div className="text-xs text-secondary mt-0.5">{doc.description}</div>}
                      </td>
                      <td>
                        <span className="badge badge-info text-xs">{doc.type}</span>
                      </td>
                      <td className="text-sm font-medium">{doc.class_name || doc.class || 'All Classes'}</td>
                      <td className="text-xs text-secondary">{dateStr}</td>
                      <td className="text-xs font-mono text-tertiary">{doc.file_size || '1.2 MB'}</td>
                      <td className="text-right">
                        <div className="flex justify-end gap-1.5 items-center">
                          <button
                            onClick={() => handleDownload(doc)}
                            className="btn btn-sm btn-ghost text-success-400 flex items-center gap-1"
                            title="Download PDF"
                          >
                            <HiOutlineDocumentArrowDown size={17} />
                            <span>Download PDF</span>
                          </button>
                          <button
                            onClick={() => handleDelete(doc.id, doc.title)}
                            className="btn btn-ghost btn-icon btn-sm text-danger-400"
                            title="Delete"
                          >
                            <HiOutlineTrash size={15} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Upload Modal */}
      {showUploadModal && (
        <div className="modal-overlay" onClick={() => !submitting && setShowUploadModal(false)}>
          <div className="modal" style={{ maxWidth: '520px' }} onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h2 className="text-lg font-bold">Upload Educational Content</h2>
              <button className="btn btn-ghost btn-icon" onClick={() => setShowUploadModal(false)} disabled={submitting}>
                <HiOutlineXMark size={20} />
              </button>
            </div>
            <form onSubmit={handleUploadSubmit}>
              <div className="modal-body space-y-4">
                <div className="form-group mb-0">
                  <label className="form-label">Document Title *</label>
                  <input
                    type="text"
                    required
                    className="form-input"
                    placeholder="e.g. Science Chapter 5 Exemplar Notes"
                    value={formData.title}
                    onChange={e => setFormData({ ...formData, title: e.target.value })}
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div className="form-group mb-0">
                    <label className="form-label">Content Type *</label>
                    <select
                      className="form-select"
                      value={formData.type}
                      onChange={e => setFormData({ ...formData, type: e.target.value })}
                    >
                      <option value="Syllabus">Syllabus</option>
                      <option value="Assignments">Assignments</option>
                      <option value="Study Material">Study Material</option>
                      <option value="Other">Other</option>
                    </select>
                  </div>
                  <div className="form-group mb-0">
                    <label className="form-label">Available For</label>
                    <input
                      type="text"
                      className="form-input"
                      placeholder="e.g. Class 10 or All Classes"
                      value={formData.class_name}
                      onChange={e => setFormData({ ...formData, class_name: e.target.value })}
                    />
                  </div>
                </div>

                <div className="form-group mb-0">
                  <label className="form-label">Description / Instructions</label>
                  <textarea
                    rows={3}
                    className="form-textarea text-sm"
                    placeholder="Brief notes for students and teachers regarding this material..."
                    value={formData.description}
                    onChange={e => setFormData({ ...formData, description: e.target.value })}
                  />
                </div>
              </div>
              <div className="modal-footer">
                <button
                  type="button"
                  className="btn btn-secondary"
                  onClick={() => setShowUploadModal(false)}
                  disabled={submitting}
                >
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary" disabled={submitting}>
                  {submitting ? 'Uploading...' : 'Publish Document'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
